name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:      # Allows you to trigger manually from Actions tab

env:
  UPSTREAM_REPO_OWNER: IvanReznikov

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the forked repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # So we can set our own credentials
          fetch-depth: 0              # Fetch full history

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream "https://github.com/${{ env.UPSTREAM_REPO_OWNER }}/mdx-langchain-conclave.git"
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --no-edit || true
      
      - name: Rebase fork on upstream
        run: |
          git checkout main
          git rebase upstream/main || git rebase --abort
          git push --force-with-lease origin main

      - name: Push changes to fork
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} main
